edition = "2023";

package kdv2001.only_metrics;

option go_package = "internal/gen/protogen/only_metrics/grpc";

// MetricType тип метрики
enum MetricType {
  UNSPECIFIED_METRIC_TYPE = 0;
  GAUGE_METRIC_TYPE = 1;
  COUNTER_METRIC_TYPE = 2;
}

service OnlyMetrics {
  rpc GetAllMetrics(GetAllMetricsReq) returns (GetAllMetricsResp);
  rpc GetMetric(GetMetricReq) returns (GetMetricResp);
  rpc UpdateMetric(UpdateMetricReq) returns (UpdateMetricResp);
  rpc UpdateMetrics(UpdateMetricsReq) returns (UpdateMetricsResp);
  rpc Ping(PingReq) returns (PingResp);
}

// GetAllMetricsReq запрос получения всех значений метрик.
message GetAllMetricsReq {}

// GetAllMetricsResp ответ получения всех значений метрик.
message GetAllMetricsResp {
  // metrics - значения метрик.
  Metrics metrics = 1;
}

// GetAllMetricsReq запрос получения значения метрики.
message GetMetricReq {
  // metric - входные параметры для получения метрики.
  Metric metric = 1;
}

// GetMetricResp ответ получения значения метрики.
message GetMetricResp {
  // metric - значение метрики.
  Metric metric = 1;
}

// UpdateMetricReq запрос для обновления значения метрики.
message UpdateMetricReq {
  // metric - значение метрики.
  Metric metric = 1;
}

// UpdateMetricResp ответ обновления значения метрики.
message UpdateMetricResp {}

// UpdateMetricResp запрос обновления значении нескольких метрик.
message UpdateMetricsReq {
  // metrics - значения метрик.
  Metrics metrics = 1;
}

// UpdateMetricsResp ответ обновления значений нескольких метрик.
message UpdateMetricsResp {}

// PingReq запрос состояния сервера.
message PingReq {}

// PingResp ответ состояния сервера.
message PingResp {
  Status status = 1;
}

// Metric поля метрики.
message Metric {
  // type - тип метрики.
  MetricType type = 1;
  // name название метрики.
  string name = 2;
  // gauge_value - значение метрики типа "градусник".
  double gauge_value = 3;
  // counter_value - значение метрики типа "счетчик".
  int64 counter_value = 4;
}

// Metrics несколько метрик.
message Metrics {
  // values - значения метрик.
  repeated Metric values = 1;
}

// Status статус сервера.
message Status {
  // description - описание.
  string description = 1;
}